#!/usr/bin/env python3
"""
generate_pdf_report.py

Generates a page-oriented PDF report with a running header, footer,
page numbers, and a data table. Requires the 'reportlab' package.

Usage:
    python generate_pdf_report.py
    python generate_pdf_report.py --input data.csv --output report.pdf --title "My Report"

Expected output:
    A .pdf file, one or more pages, each with a title header at the
    top, a footer showing "Page X of Y" and the generation date, and
    a formatted table of the report data in the body.
"""

import argparse
import csv
import datetime
import os
import sys

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Spacer
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import Paragraph
except ImportError:
    print("Missing dependency 'reportlab'. Install it with: pip install reportlab", file=sys.stderr)
    sys.exit(1)


def load_sample_data():
    headers = ["Invoice #", "Client", "Amount (USD)", "Due Date", "Status"]
    rows = [
        ["INV-1001", "Acme Corp", "1,250.00", "2026-07-20", "Unpaid"],
        ["INV-1002", "Globex Inc", "3,400.50", "2026-07-15", "Paid"],
        ["INV-1003", "Initech", "890.00", "2026-08-01", "Unpaid"],
        ["INV-1004", "Umbrella LLC", "5,600.00", "2026-07-10", "Overdue"],
    ]
    return headers, rows


def load_csv_data(path):
    with open(path, newline="", encoding="utf-8") as f:
        rows = list(csv.reader(f))
    if not rows:
        raise ValueError("CSV file is empty.")
    return rows[0], rows[1:]


class PDFReport:
    """Handles header/footer drawing on every page."""

    def __init__(self, title):
        self.title = title
        self.generated_at = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def header_footer(self, canvas, doc):
        canvas.saveState()
        width, height = A4

        # Header
        canvas.setFont("Helvetica-Bold", 11)
        canvas.setFillColor(colors.HexColor("#1d4ed8"))
        canvas.drawString(2 * cm, height - 1.4 * cm, self.title)
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.grey)
        canvas.drawRightString(width - 2 * cm, height - 1.4 * cm, self.generated_at)
        canvas.setStrokeColor(colors.HexColor("#e2e8f0"))
        canvas.line(2 * cm, height - 1.6 * cm, width - 2 * cm, height - 1.6 * cm)

        # Footer
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.grey)
        page_num_text = f"Page {doc.page}"
        canvas.drawCentredString(width / 2, 1.2 * cm, page_num_text)
        canvas.drawString(2 * cm, 1.2 * cm, "Generated by generate_pdf_report.py")
        canvas.restoreState()


def build_pdf(headers, rows, title, output_path):
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        topMargin=2.2 * cm,
        bottomMargin=2 * cm,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph(f"<b>{title}</b>", styles["Title"]))
    elements.append(Spacer(1, 6))
    elements.append(Paragraph(f"Total records: {len(rows)}", styles["Normal"]))
    elements.append(Spacer(1, 14))

    table_data = [headers] + rows
    table = Table(table_data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563eb")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f1f5f9")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(table)

    report = PDFReport(title)
    doc.build(elements, onFirstPage=report.header_footer, onLaterPages=report.header_footer)


def main():
    parser = argparse.ArgumentParser(description="Generate a page-oriented PDF report from CSV data.")
    parser.add_argument("--input", "-i", help="Path to input CSV file. If omitted, sample data is used.")
    parser.add_argument("--output", "-o", default="report.pdf", help="Path to output PDF file (default: report.pdf)")
    parser.add_argument("--title", "-t", default="Invoice Summary Report", help="Report title")
    args = parser.parse_args()

    if args.input:
        if not os.path.isfile(args.input):
            print(f"Error: input file not found: {args.input}", file=sys.stderr)
            sys.exit(1)
        headers, rows = load_csv_data(args.input)
    else:
        headers, rows = load_sample_data()
        print("No --input provided, using built-in sample data.")

    build_pdf(headers, rows, args.title, args.output)

    print(f"PDF report written to: {os.path.abspath(args.output)}")
    print("Open it with any PDF viewer.")


if __name__ == "__main__":
    main()
