#!/usr/bin/env python3
"""
migration_scripts.py
=======================
Set up and drive Alembic database migrations from Python — initialize
an Alembic environment pointed at a database, autogenerate a revision
from SQLAlchemy models, and upgrade/downgrade the schema.

Usage
-----
    # 1. Initialize an Alembic project (creates ./migrations/ + alembic.ini)
    python migration_scripts.py --action init --db-url sqlite:///sample.db

    # 2. Create a new revision (autogenerated from the models in this file)
    python migration_scripts.py --action revision --message "create employees table"

    # 3. Apply all pending migrations
    python migration_scripts.py --action upgrade

    # 4. Roll back the most recent migration
    python migration_scripts.py --action downgrade

    # 5. Show migration history / current version
    python migration_scripts.py --action history
    python migration_scripts.py --action current

If run with no arguments at all, the script runs --action init followed
by --action revision and --action upgrade against a local sample.db, so
you can see the full workflow end-to-end.

Expected output
----------------
- init: creates a `migrations/` directory and `alembic.ini` in the
  current folder, wired to --db-url.
- revision: creates a new file under `migrations/versions/` containing
  the detected schema changes (upgrade()/downgrade() functions).
- upgrade/downgrade: applies/reverts migrations and prints the
  resulting schema version.
- history/current: prints the revision history or the currently
  applied revision.

CAUTION
-------
- --action upgrade/downgrade change your database schema. Point
  --db-url at a test/development database, and take a backup first
  (see backup_database.py) before running against anything important.
- Autogenerate detects differences between the SQLAlchemy models
  defined in this script's MODELS section and the live database — it
  is a helpful starting point, not a guarantee; always review the
  generated migration file before applying it.

Requirements
------------
    pip install alembic sqlalchemy
"""

import argparse
import os
import subprocess
import sys

MIGRATIONS_DIR = "migrations"
ALEMBIC_INI = "alembic.ini"

# --- Example SQLAlchemy models used for autogeneration ---------------------
MODELS_MODULE_CONTENT = '''
"""Example models used by migration_scripts.py for autogenerate."""
from sqlalchemy import Column, Integer, String, Float
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class Employee(Base):
    __tablename__ = "employees"

    id = Column(Integer, primary_key=True)
    name = Column(String(120), nullable=False)
    department = Column(String(80))
    salary = Column(Float)
'''

ENV_PY_TEMPLATE = '''"""Alembic environment configured to autogenerate from models.py"""
import sys
import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

sys.path.insert(0, os.getcwd())
from models import Base  # noqa: E402

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def run_migrations_offline():
    url = config.get_main_option("sqlalchemy.url")
    context.configure(url=url, target_metadata=target_metadata, literal_binds=True)
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''


def check_alembic_installed():
    try:
        import alembic  # noqa: F401
    except ImportError:
        print("[error] alembic is not installed. Run: pip install alembic sqlalchemy")
        sys.exit(1)


def run_alembic(args_list):
    print(f"[info] Running: alembic {' '.join(args_list)}")
    result = subprocess.run(["alembic"] + args_list, capture_output=True, text=True)
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr)
        sys.exit(1)


def action_init(db_url: str):
    if os.path.exists(MIGRATIONS_DIR):
        print(f"[warning] '{MIGRATIONS_DIR}' already exists, skipping alembic init")
    else:
        run_alembic(["init", MIGRATIONS_DIR])

    with open("models.py", "w", encoding="utf-8") as f:
        f.write(MODELS_MODULE_CONTENT)
    print("[info] Wrote models.py with an example 'Employee' model")

    env_py_path = os.path.join(MIGRATIONS_DIR, "env.py")
    with open(env_py_path, "w", encoding="utf-8") as f:
        f.write(ENV_PY_TEMPLATE)
    print(f"[info] Rewrote {env_py_path} to autogenerate from models.Base.metadata")

    with open(ALEMBIC_INI, "r", encoding="utf-8") as f:
        content = f.read()
    content = content.replace(
        "sqlalchemy.url = driver://user:pass@localhost/dbname",
        f"sqlalchemy.url = {db_url}",
    )
    with open(ALEMBIC_INI, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[success] Alembic initialized. {ALEMBIC_INI} configured with: {db_url}")


def action_revision(message: str):
    run_alembic(["revision", "--autogenerate", "-m", message])
    print("[success] New revision created under migrations/versions/. Review it before upgrading.")


def action_upgrade(revision: str = "head"):
    run_alembic(["upgrade", revision])
    print(f"[success] Database upgraded to revision: {revision}")


def action_downgrade(revision: str = "-1"):
    run_alembic(["downgrade", revision])
    print(f"[success] Database downgraded by: {revision}")


def action_history():
    run_alembic(["history"])


def action_current():
    run_alembic(["current"])


def main():
    parser = argparse.ArgumentParser(description="Drive Alembic migrations for version-controlled schema changes.")
    parser.add_argument("--action", choices=["init", "revision", "upgrade", "downgrade", "history", "current"], default=None)
    parser.add_argument("--db-url", default="sqlite:///sample.db", help="SQLAlchemy database URL (init action)")
    parser.add_argument("--message", default="auto migration", help="Message for a new revision")
    parser.add_argument("--revision", default=None, help="Target revision for upgrade/downgrade (default: head / -1)")
    args = parser.parse_args()

    check_alembic_installed()

    if args.action is None:
        print("[info] No --action given, running the full demo workflow: init -> revision -> upgrade")
        action_init(args.db_url)
        action_revision(args.message)
        action_upgrade(args.revision or "head")
        return

    if args.action == "init":
        action_init(args.db_url)
    elif args.action == "revision":
        action_revision(args.message)
    elif args.action == "upgrade":
        action_upgrade(args.revision or "head")
    elif args.action == "downgrade":
        action_downgrade(args.revision or "-1")
    elif args.action == "history":
        action_history()
    elif args.action == "current":
        action_current()


if __name__ == "__main__":
    main()
