#!/usr/bin/env python3
"""
documentation_generation.py

Demonstrates auto-generating HTML documentation from Python docstrings
using Sphinx: scaffolds a minimal Sphinx project (conf.py + index.rst),
points `sphinx-apidoc` at a sample module full of docstrings, and (if
Sphinx is installed) builds the final HTML docs automatically.

Usage:
    pip install sphinx
    python documentation_generation.py
    python documentation_generation.py --outdir mydocs

Expected output:
    A folder (default: docs_demo/) containing:
      docs_demo/
        sample_module.py        <- a small module with real docstrings
        source/
          conf.py
          index.rst
        build/html/index.html   <- the generated documentation (if Sphinx ran)

    If Sphinx is installed, the script runs `sphinx-apidoc` and
    `sphinx-build` for you and prints the path to the generated
    index.html — open it in a browser to see the rendered docs. If
    Sphinx isn't installed, the script still scaffolds everything and
    prints the exact commands to run once you install it.
"""

import argparse
import os
import shutil
import subprocess
import sys


SAMPLE_MODULE = '''"""
sample_module

A tiny example module with real docstrings, used to demonstrate
Sphinx's ability to auto-generate documentation from docstrings
(via the autodoc extension) instead of maintaining separate docs
by hand.
"""


def add(a: int, b: int) -> int:
    """
    Add two integers together.

    :param a: The first number.
    :param b: The second number.
    :return: The sum of ``a`` and ``b``.
    """
    return a + b


class Greeter:
    """A simple greeter class, used to demonstrate class + method docs."""

    def __init__(self, name: str):
        """
        :param name: The name to greet.
        """
        self.name = name

    def greet(self) -> str:
        """Return a friendly greeting string for :attr:`name`."""
        return f"Hello, {self.name}!"
'''

CONF_PY_TEMPLATE = '''# Minimal Sphinx configuration, generated by documentation_generation.py
import os
import sys
sys.path.insert(0, os.path.abspath("../.."))

project = "{project_name}"
extensions = ["sphinx.ext.autodoc", "sphinx.ext.napoleon"]
html_theme = "alabaster"
'''

INDEX_RST_TEMPLATE = '''{title}
{underline}

.. automodule:: sample_module
   :members:
   :undoc-members:
   :show-inheritance:
'''


def scaffold_sphinx_project(outdir: str, project_name: str) -> str:
    source_dir = os.path.join(outdir, "source")
    os.makedirs(source_dir, exist_ok=True)

    with open(os.path.join(outdir, "sample_module.py"), "w", encoding="utf-8") as f:
        f.write(SAMPLE_MODULE)

    with open(os.path.join(source_dir, "conf.py"), "w", encoding="utf-8") as f:
        f.write(CONF_PY_TEMPLATE.format(project_name=project_name))

    title = f"{project_name} Documentation"
    with open(os.path.join(source_dir, "index.rst"), "w", encoding="utf-8") as f:
        f.write(INDEX_RST_TEMPLATE.format(title=title, underline="=" * len(title)))

    return source_dir


def build_docs(outdir: str, source_dir: str) -> bool:
    """Run sphinx-build to generate HTML docs. Returns True on success."""
    build_dir = os.path.join(outdir, "build", "html")
    sphinx_build = shutil.which("sphinx-build")
    if not sphinx_build:
        return False

    try:
        subprocess.run(
            [sphinx_build, "-b", "html", source_dir, build_dir],
            check=True,
            capture_output=True,
            text=True,
            cwd=outdir,
        )
        return True
    except subprocess.CalledProcessError as e:
        print("sphinx-build failed:")
        print(e.stdout)
        print(e.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(description="Scaffold and build Sphinx documentation from docstrings.")
    parser.add_argument("--outdir", default="docs_demo", help="Output folder (default: docs_demo)")
    parser.add_argument("--project-name", default="SampleAutomationTool", help="Sphinx project name")
    args = parser.parse_args()

    print("Documentation Generation Demo (Sphinx)")
    print("=" * 45)

    source_dir = scaffold_sphinx_project(args.outdir, args.project_name)
    print(f"Scaffolded Sphinx project at: {os.path.abspath(args.outdir)}")
    print(f"  - sample module with docstrings: {args.outdir}/sample_module.py")
    print(f"  - Sphinx config:                 {source_dir}/conf.py")
    print(f"  - Sphinx index:                  {source_dir}/index.rst")

    built = build_docs(args.outdir, source_dir)

    if built:
        html_index = os.path.abspath(os.path.join(args.outdir, "build", "html", "index.html"))
        print(f"\nHTML documentation built successfully:")
        print(f"  {html_index}")
        print("Open that file in a browser to see the docs generated from the docstrings above.")
    else:
        print("\nSphinx is not installed (or sphinx-build was not found on PATH), so the HTML build was skipped.")
        print("Install it and build manually with:")
        print("  pip install sphinx")
        print(f"  sphinx-build -b html {source_dir} {os.path.join(args.outdir, 'build', 'html')}")


if __name__ == "__main__":
    main()
